-- ═══════════════════════════════════════════════════════════
-- MetaBreath Pilot Test 14-16 July — DRY RUN v2
-- Generated by scripts/import_pilot_excel_v2_dryrun.py
-- Source: /Users/ciy_th/Downloads/MetaBreath Pilot Test 14-16 July.xlsx
-- Day 1 inserts are idempotent (ON CONFLICT (time,device_id) DO NOTHING)
-- ═══════════════════════════════════════════════════════════
BEGIN;

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 07:39 | Benjamars → benjamars
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 51, height_cm = 157
  WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:39:55.704000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260714',
   0.7, 0.7057, 5.7,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดมาก", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:40:55.704000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260714',
   0.7, 0.7169, 16.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:41:55.704000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'f91389a9-2ed7-460e-9767-51d0b83ab6c5', '1d605079-f882-4408-93b2-ff63608fca76', '2026-07-14 07:39:55.704000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
     AND ts = '2026-07-14 07:39:55.704000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 07:52 | Wan → Wan
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 63, height_cm = 163
  WHERE user_id = '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:52:50.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260714',
   0.7, 0.7154, 15.4,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "ไข่ต้ม", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:53:50.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:54:50.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'ec48c3ac-3531-4bd3-81e7-82308c13a922', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81', '2026-07-14 07:52:50.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81'
     AND ts = '2026-07-14 07:52:50.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 09:13 | Toom → toom
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 90, height_cm = 175
  WHERE user_id = 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:13:07.153000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260714',
   0.7, 0.7105, 10.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล)", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 7 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:14:07.153000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260714',
   0.7, 0.7073, 7.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:15:07.153000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260714',
   0.7, 0.7161, 16.1,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '5a26eed9-50e2-49ee-b27d-ac4bd5a24d1b', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800', '2026-07-14 09:13:07.153000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800'
     AND ts = '2026-07-14 09:13:07.153000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 09:13 | man → man
-- ═══════════════════════════════════════════════════════════
-- FORCE override profile (Day 1 self-report was wrong)
UPDATE profiles SET weight_kg = 53, height_cm = 172
  WHERE user_id = 'ed06c0bb-598c-43a9-8439-04b5b9da5796';
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:13:11.247000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260714',
   0.7, 0.7073, 7.3,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "หลัง 22.00 น. ของเมื่อวาน", "last_meal_type": "ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดมาก", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:14:11.247000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:15:11.247000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260714',
   0.7, 0.7137, 13.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '7331c23b-e985-4e7b-a06e-13310a13213a', 'ed06c0bb-598c-43a9-8439-04b5b9da5796', '2026-07-14 09:13:11.247000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'ed06c0bb-598c-43a9-8439-04b5b9da5796'
     AND ts = '2026-07-14 09:13:11.247000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 09:17 | Aor → aor
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 47, height_cm = 149
  WHERE user_id = '5f774478-267b-4f16-9c77-efe45aee5b29'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:17:04.933000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260714',
   0.7, 0.7071, 7.1,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:18:04.933000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260714',
   0.7, 0.7089, 8.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:19:04.933000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260714',
   0.7, 0.7105, 10.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'bda34599-ea67-40ae-b338-49494979b20b', '5f774478-267b-4f16-9c77-efe45aee5b29', '2026-07-14 09:17:04.933000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '5f774478-267b-4f16-9c77-efe45aee5b29'
     AND ts = '2026-07-14 09:17:04.933000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 09:19 | Pui → pui
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 53, height_cm = 154
  WHERE user_id = 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:19:05.827000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260714',
   0.7, 0.7105, 10.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:20:05.827000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260714',
   0.7, 0.7056, 5.6,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:21:05.827000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260714',
   0.7, 0.704, 4.0,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'b46ab63f-a3c3-4ade-a15a-057b54fa8e3a', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d', '2026-07-14 09:19:05.827000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d'
     AND ts = '2026-07-14 09:19:05.827000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 09:21 | Araya → araya
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 64, height_cm = 156
  WHERE user_id = '5cebe88b-3f66-4987-98d0-4b328a8ec026'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:21:11.996000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260714',
   0.7, 0.708, 8.0,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:22:11.996000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260714',
   0.7, 0.7153, 15.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:23:11.996000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260714',
   0.7, 0.7169, 16.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '562fd061-f102-4ab7-b071-e9670b3178d8', '5cebe88b-3f66-4987-98d0-4b328a8ec026', '2026-07-14 09:21:11.996000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '5cebe88b-3f66-4987-98d0-4b328a8ec026'
     AND ts = '2026-07-14 09:21:11.996000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 09:29 | Mark → mark
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 71.5, height_cm = 176
  WHERE user_id = '6dee7753-311a-469c-9086-f8d1265b2c5f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:29:32.340000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260714',
   0.7, 0.7242, 24.2,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 2 สีส้มอ่อน"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:30:32.340000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260714',
   0.7, 0.7177, 17.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:31:32.340000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260714',
   0.7, 0.7113, 11.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'f216cea0-531d-4bc5-86b1-dc953372d120', '6dee7753-311a-469c-9086-f8d1265b2c5f', '2026-07-14 09:29:32.340000', 1.5,
       'excel_pilot_import', 'imported: ระดับ 2 สีส้มอ่อน',
       'urine', 'small', 15.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '6dee7753-311a-469c-9086-f8d1265b2c5f'
     AND ts = '2026-07-14 09:29:32.340000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-14 10:48 | Orasinee → orasinee
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 56, height_cm = 150
  WHERE user_id = 'fa35f4bd-e360-4aa9-8d25-7c734253c64f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:48:02.608000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260714',
   0.7, 0.7177, 17.7,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:49:02.608000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260714',
   0.7, 0.7056, 5.6,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:50:02.608000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260714',
   0.7, 0.7048, 4.8,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'd72f5f49-791d-4665-ae3e-2f3b040002d8', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f', '2026-07-14 10:48:02.608000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'fa35f4bd-e360-4aa9-8d25-7c734253c64f'
     AND ts = '2026-07-14 10:48:02.608000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 07:58 | Wan → Wan
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 63, height_cm = 163
  WHERE user_id = '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 07:58:22.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260715',
   0.7, 0.7193, 19.3,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 07:59:22.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260715',
   0.7, 0.7091, 9.1,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:00:22.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260715',
   0.7, 0.7097, 9.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'f6428317-1ee0-4452-8d2b-a5615725ba37', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81', '2026-07-15 07:58:22.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81'
     AND ts = '2026-07-15 07:58:22.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 08:06 | Aor → aor
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 46.25, height_cm = 149
  WHERE user_id = '5f774478-267b-4f16-9c77-efe45aee5b29'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:06:46.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260715',
   0.7, 0.7137, 13.7,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:07:46.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260715',
   0.7, 0.7089, 8.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:08:46.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260715',
   0.7, 0.7056, 5.6,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'ba332bad-fc69-4c60-ab09-05852331775e', '5f774478-267b-4f16-9c77-efe45aee5b29', '2026-07-15 08:06:46.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '5f774478-267b-4f16-9c77-efe45aee5b29'
     AND ts = '2026-07-15 08:06:46.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 08:13 | Araya → araya
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 64, height_cm = 156
  WHERE user_id = '5cebe88b-3f66-4987-98d0-4b328a8ec026'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:13:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260715',
   0.7, 0.7218, 21.8,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:14:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260715',
   0.7, 0.7137, 13.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:15:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260715',
   0.7, 0.7097, 9.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '42234bbb-2ee4-448e-b601-7ba0f84433e9', '5cebe88b-3f66-4987-98d0-4b328a8ec026', '2026-07-15 08:13:44.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '5cebe88b-3f66-4987-98d0-4b328a8ec026'
     AND ts = '2026-07-15 08:13:44.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 08:27 | Mark → mark
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 71.5, height_cm = 176
  WHERE user_id = '6dee7753-311a-469c-9086-f8d1265b2c5f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:27:34.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260715',
   0.7, 0.7153, 15.3,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:28:34.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260715',
   0.7, 0.7177, 17.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:29:34.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260715',
   0.7, 0.7089, 8.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '00c0fb66-f5ef-42de-8419-46699c8fcf24', '6dee7753-311a-469c-9086-f8d1265b2c5f', '2026-07-15 08:27:34.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '6dee7753-311a-469c-9086-f8d1265b2c5f'
     AND ts = '2026-07-15 08:27:34.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 08:53 | man → man
-- ═══════════════════════════════════════════════════════════
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:53:13.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260715',
   0.7, 0.7218, 21.8,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:54:13.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260715',
   0.7, 0.7129, 12.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 08:55:13.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260715',
   0.7, 0.7049, 4.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'ef3512ff-9f88-4117-a005-f0afcc7eaa39', 'ed06c0bb-598c-43a9-8439-04b5b9da5796', '2026-07-15 08:53:13.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'ed06c0bb-598c-43a9-8439-04b5b9da5796'
     AND ts = '2026-07-15 08:53:13.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 09:04 | Orasinee → orasinee
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 56, height_cm = 150
  WHERE user_id = 'fa35f4bd-e360-4aa9-8d25-7c734253c64f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 09:04:04.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260715',
   0.7, 0.7137, 13.7,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 7 ชั่วโมง", "exercise_intensity": "เบา", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 09:05:04.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260715',
   0.7, 0.7048, 4.8,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 09:06:04.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260715',
   0.7, 0.7121, 12.1,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'b098ff53-3c6d-446b-b460-e47887719094', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f', '2026-07-15 09:04:04.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'fa35f4bd-e360-4aa9-8d25-7c734253c64f'
     AND ts = '2026-07-15 09:04:04.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 09:28 | Toom → toom
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 90, height_cm = 175
  WHERE user_id = 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 09:28:57.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260715',
   0.7, 0.7089, 8.9,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล)", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 7 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 09:29:57.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260715',
   0.7, 0.7056, 5.6,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 09:30:57.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260715',
   0.7, 0.7089, 8.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'da6d60af-57ab-4a8f-8b19-a19d86cf5ec6', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800', '2026-07-15 09:28:57.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800'
     AND ts = '2026-07-15 09:28:57.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 10:36 | Pui → pui
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 53, height_cm = 154
  WHERE user_id = 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 10:36:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260715',
   0.7, 0.7129, 12.9,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 10:37:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260715',
   0.7, 0.7113, 11.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 10:38:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260715',
   0.7, 0.7193, 19.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '633a7878-1f59-42e4-a878-9cafd0239243', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d', '2026-07-15 10:36:44.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d'
     AND ts = '2026-07-15 10:36:44.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-15 23:57 | Benjamars → benjamars
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 52, height_cm = 156
  WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 23:57:46.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260715',
   0.7, 0.7266, 26.6,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_15", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดที่สุด", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 23:58:46.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260715',
   0.7, 0.7121, 12.1,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-15 23:59:46.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260715',
   0.7, 0.7041, 4.1,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'd6ff4b12-2940-4bc0-86ea-d6e2df3d722d', '1d605079-f882-4408-93b2-ff63608fca76', '2026-07-15 23:57:46.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
     AND ts = '2026-07-15 23:57:46.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 08:50 | Aor → aor
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 46, height_cm = 149
  WHERE user_id = '5f774478-267b-4f16-9c77-efe45aee5b29'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 08:50:10.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260716',
   0.7, 0.7129, 12.9,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 08:51:10.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260716',
   0.7, 0.7073, 7.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 08:52:10.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260716',
   0.7, 0.7137, 13.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'dfcc267b-3b4c-4707-b854-d8b9f7de83d4', '5f774478-267b-4f16-9c77-efe45aee5b29', '2026-07-16 08:50:10.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '5f774478-267b-4f16-9c77-efe45aee5b29'
     AND ts = '2026-07-16 08:50:10.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 08:52 | man → man
-- ═══════════════════════════════════════════════════════════
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 08:52:01.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260716',
   0.7, 0.7153, 15.3,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 7 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 08:53:01.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260716',
   0.7, 0.7121, 12.1,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 08:54:01.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260716',
   0.7, 0.7113, 11.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'b9360c14-f1a4-42cb-996c-59c270020f45', 'ed06c0bb-598c-43a9-8439-04b5b9da5796', '2026-07-16 08:52:01.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'ed06c0bb-598c-43a9-8439-04b5b9da5796'
     AND ts = '2026-07-16 08:52:01.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 09:06 | Wan → Wan
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 63, height_cm = 163
  WHERE user_id = '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:06:02.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260716',
   0.7, 0.7185, 18.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "เบา", "stress_today": "เครียดนิดหน่อย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:07:02.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260716',
   0.7, 0.7129, 12.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:08:02.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260716',
   0.7, 0.7201, 20.1,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'cd2b82e3-2a01-485e-9152-4d92104eb158', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81', '2026-07-16 09:06:02.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81'
     AND ts = '2026-07-16 09:06:02.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 09:15 | Benjamars → benjamars
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 52, height_cm = 157
  WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:15:23.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260716',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดปานกลาง", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:16:23.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260716',
   0.7, 0.7073, 7.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:17:23.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260716',
   0.7, 0.7089, 8.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '88ec872e-1100-4403-8e9a-e018068fbfee', '1d605079-f882-4408-93b2-ff63608fca76', '2026-07-16 09:15:23.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
     AND ts = '2026-07-16 09:15:23.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 09:21 | Araya → araya
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 64, height_cm = 156
  WHERE user_id = '5cebe88b-3f66-4987-98d0-4b328a8ec026'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:21:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260716',
   0.7, 0.7435, 43.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:22:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260716',
   0.7, 0.7258, 25.8,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:23:44.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260716',
   0.7, 0.7274, 27.4,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'e1d883bb-266b-497e-ace7-5fd6fb1b5b13', '5cebe88b-3f66-4987-98d0-4b328a8ec026', '2026-07-16 09:21:44.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '5cebe88b-3f66-4987-98d0-4b328a8ec026'
     AND ts = '2026-07-16 09:21:44.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 09:26 | Orasinee → orasinee
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 56, height_cm = 150
  WHERE user_id = 'fa35f4bd-e360-4aa9-8d25-7c734253c64f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:26:40.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260716',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:27:40.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260716',
   0.7, 0.7129, 12.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:28:40.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260716',
   0.7, 0.7097, 9.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT '6eeeac23-dbbb-4a50-8f80-af0f98a203b3', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f', '2026-07-16 09:26:40.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'fa35f4bd-e360-4aa9-8d25-7c734253c64f'
     AND ts = '2026-07-16 09:26:40.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 09:37 | Pui → pui
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 53, height_cm = 154
  WHERE user_id = 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:37:34.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260716',
   0.7, 0.7113, 11.3,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "เบา", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:38:34.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260716',
   0.7, 0.704, 4.0,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:39:34.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260716',
   0.7, 0.7113, 11.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'de55a46f-7239-44d3-8888-073b10cbf11c', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d', '2026-07-16 09:37:34.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d'
     AND ts = '2026-07-16 09:37:34.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 09:38 | Mark → mark
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 71.5, height_cm = 176
  WHERE user_id = '6dee7753-311a-469c-9086-f8d1265b2c5f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:38:35.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260716',
   0.7, 0.7162, 16.2,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "หนัก", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 2 สีส้มอ่อน"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:39:35.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260716',
   0.7, 0.7129, 12.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 09:40:35.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260716',
   0.7, 0.7097, 9.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'f9f8b0ba-93a6-4ed0-b79a-c4a6da52fc93', '6dee7753-311a-469c-9086-f8d1265b2c5f', '2026-07-16 09:38:35.000000', 1.5,
       'excel_pilot_import', 'imported: ระดับ 2 สีส้มอ่อน',
       'urine', 'small', 15.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = '6dee7753-311a-469c-9086-f8d1265b2c5f'
     AND ts = '2026-07-16 09:38:35.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- 2026-07-16 10:12 | Toom → toom
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 90, height_cm = 175
  WHERE user_id = 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 10:12:03.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260716',
   0.7, 0.7185, 18.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_16", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล)", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 7 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 10:13:03.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260716',
   0.7, 0.7169, 16.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-16 10:14:03.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260716',
   0.7, 0.7137, 13.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
SELECT 'a617eec2-898d-46db-ab99-0bbcc4d5718d', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800', '2026-07-16 10:12:03.000000', 0.5,
       'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
       'urine', 'trace', 5.0
WHERE NOT EXISTS (
  SELECT 1 FROM ketone_logs
   WHERE user_id = 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800'
     AND ts = '2026-07-16 10:12:03.000000'
     AND source = 'excel_pilot_import'
);

-- ═══════════════════════════════════════════════════════════
-- Processed 27 data rows
-- ═══════════════════════════════════════════════════════════
-- Applied against production 2026-07-17.
COMMIT;
