-- ═══════════════════════════════════════════════════════════
-- MetaBreath Pilot Test import — DRY RUN
-- Generated by scripts/import_pilot_excel_dryrun.py
-- Source: /Users/ciy_th/Downloads/MetaBreath Pilot Test 14 July.xlsx
-- ═══════════════════════════════════════════════════════════
BEGIN;

-- ═══════════════════════════════════════════════════════════
-- User: Test1 → db=test1 (id=1d8b7ffd…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 58, height_cm = 160
  WHERE user_id = '1d8b7ffd-1ae8-4ecb-9982-c4b364268e6f'
    AND (weight_kg IS NULL OR height_cm IS NULL);

-- ═══════════════════════════════════════════════════════════
-- User: เบญจมาศ → db=benjamars (id=1d605079…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 51, height_cm = 157
  WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('6ffba8a8-e9da-46e9-8eb7-1995cffa13a7', '1d605079-f882-4408-93b2-ff63608fca76', '2026-07-13 21:44:10.234000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: Benjamars → db=benjamars (id=1d605079…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 51, height_cm = 157
  WHERE user_id = '1d605079-f882-4408-93b2-ff63608fca76'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:39:55.704000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260714',
   0.7, 0.7057, 5.7,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดมาก", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:40:55.704000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260714',
   0.7, 0.7169, 16.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 07:41:55.704000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '1d605079-f882-4408-93b2-ff63608fca76',
   'benjamars-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('0c845327-2542-4b32-b0c4-2a240b5c94b0', '1d605079-f882-4408-93b2-ff63608fca76', '2026-07-14 07:39:55.704000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: Wan → db=Wan (id=7aaa453c…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 63, height_cm = 163
  WHERE user_id = '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:00:00.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "ไข่ต้ม", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:01:00.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:02:00.000000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81',
   'wan-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('33db54f6-46bc-49d9-860a-f61ed56d735f', '7aaa453c-a8d2-4cf2-b61b-c8cdb3894d81', '2026-07-14 10:00:00.000000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: toom → db=toom (id=bdaeb6d8…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 90, height_cm = 175
  WHERE user_id = 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:13:07.153000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260714',
   0.7, 0.7105, 10.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล)", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 7 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:14:07.153000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260714',
   0.7, 0.7073, 7.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:15:07.153000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800',
   'toom-pilot-20260714',
   0.7, 0.7146, 14.6,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('de022361-ee6d-4c35-810f-d4b5306b2859', 'bdaeb6d8-b877-49ba-9f3a-556bbfa09800', '2026-07-14 09:13:07.153000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: man → db=man (id=ed06c0bb…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 51, height_cm = 157
  WHERE user_id = 'ed06c0bb-598c-43a9-8439-04b5b9da5796'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:13:11.247000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260714',
   0.7, 0.7073, 7.3,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "หลัง 22.00 น. ของเมื่อวาน", "last_meal_type": "ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดมาก", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:14:11.247000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260714',
   0.7, 0.7145, 14.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:15:11.247000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ed06c0bb-598c-43a9-8439-04b5b9da5796',
   'man-pilot-20260714',
   0.7, 0.7137, 13.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('3e78c1d2-1270-4094-8c84-9656421aeed7', 'ed06c0bb-598c-43a9-8439-04b5b9da5796', '2026-07-14 09:13:11.247000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: Aor → db=aor (id=5f774478…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 47, height_cm = 149
  WHERE user_id = '5f774478-267b-4f16-9c77-efe45aee5b29'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:17:04.933000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260714',
   0.7, 0.7071, 7.1,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:18:04.933000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260714',
   0.7, 0.7089, 8.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:19:04.933000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5f774478-267b-4f16-9c77-efe45aee5b29',
   'aor-pilot-20260714',
   0.7, 0.7105, 10.5,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('feb90a54-5bd0-44eb-bc7a-d25b5c37c9e9', '5f774478-267b-4f16-9c77-efe45aee5b29', '2026-07-14 09:17:04.933000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: Pui → db=pui (id=ee1eee64…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 53, height_cm = 154
  WHERE user_id = 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:19:05.827000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260714',
   0.7, 0.7105, 10.5,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:20:05.827000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260714',
   0.7, 0.7056, 5.6,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:21:05.827000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d',
   'pui-pilot-20260714',
   0.7, 0.704, 4.0,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('26a9d25a-6330-4768-b1cd-d1ae18eaacaf', 'ee1eee64-a65a-4a5f-893b-4b49e8ba335d', '2026-07-14 09:19:05.827000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: Araya → db=araya (id=5cebe88b…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 64, height_cm = 156
  WHERE user_id = '5cebe88b-3f66-4987-98d0-4b328a8ec026'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:21:11.996000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260714',
   0.7, 0.708, 8.0,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "ไม่เครียดเลย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:22:11.996000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260714',
   0.7, 0.7153, 15.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:23:11.996000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '5cebe88b-3f66-4987-98d0-4b328a8ec026',
   'araya-pilot-20260714',
   0.7, 0.7169, 16.9,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('262c22a5-e4cd-464f-a4b4-909ec764a06c', '5cebe88b-3f66-4987-98d0-4b328a8ec026', '2026-07-14 09:21:11.996000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- User: Mark → db=mark (id=6dee7753…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 71.5, height_cm = 176
  WHERE user_id = '6dee7753-311a-469c-9086-f8d1265b2c5f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:29:32.340000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260714',
   0.7, 0.7242, 24.2,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "20.00-22.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง", "alcohol_24h": "ไม่ใช่", "sleep_hours": "ประมาณ 6 ชั่วโมง", "exercise_intensity": "ปานกลาง", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 2 สีส้มอ่อน"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:30:32.340000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260714',
   0.7, 0.7177, 17.7,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 09:31:32.340000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', '6dee7753-311a-469c-9086-f8d1265b2c5f',
   'mark-pilot-20260714',
   0.7, 0.7113, 11.3,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('735ab718-0dab-4df6-ac73-e1884d8127f2', '6dee7753-311a-469c-9086-f8d1265b2c5f', '2026-07-14 09:29:32.340000', 1.5,
   'excel_pilot_import', 'imported: ระดับ 2 สีส้มอ่อน',
   'urine', 'small', 15.0);

-- ═══════════════════════════════════════════════════════════
-- User: Orasinee → db=orasinee (id=fa35f4bd…)
-- ═══════════════════════════════════════════════════════════
UPDATE profiles SET weight_kg = 56, height_cm = 150
  WHERE user_id = 'fa35f4bd-e360-4aa9-8d25-7c734253c64f'
    AND (weight_kg IS NULL OR height_cm IS NULL);
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:48:02.608000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260714',
   0.7, 0.7177, 17.7,
   100, 95, 0.05,
   0.95, 'low', '{"source": "excel_pilot_import_2026_07_14", "age_range": "40-55 ปี", "last_meal_time": "16.00-19.00 น. ของเมื่อวาน", "last_meal_type": "คาร์โบไฮเดรตสูง (ข้าว/แป้ง/น้ำตาล), โปรตีนสูง, ผักผลไม้เป็นหลัก", "alcohol_24h": "ไม่ใช่", "sleep_hours": "น้อยกว่า 6 ชั่วโมง", "exercise_intensity": "ไม่ได้ออกกำลังกาย", "stress_today": "เครียดนิดหน่อย", "medication": "ไม่ได้ใช้", "smoke_2h": "ไม่ใช่", "brush_30m": "ไม่ใช่", "urine_level_note": "ระดับ 1 สีนู้ด"}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:49:02.608000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260714',
   0.7, 0.7056, 5.6,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO sensor_readings
  (time, device_id, user_id, session_id,
   ambient_voc, breath_voc, acetone_delta,
   quality_score, reliability_score, environment_penalty,
   confidence_score, label, raw)
VALUES
  ('2026-07-14 10:50:02.608000', 'a1fe4813-ff62-4efb-8f29-af5c7d4f824e', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f',
   'orasinee-pilot-20260714',
   0.7, 0.7048, 4.8,
   100, 95, 0.05,
   0.95, 'low', '{}'::jsonb)
ON CONFLICT (time, device_id) DO NOTHING;
INSERT INTO ketone_logs
  (id, user_id, ts, value_mmol, source, note,
   ketone_type, urine_category, urine_mg_dl)
VALUES
  ('6cb79475-ffe0-4019-a2a0-3752cb9c5e3b', 'fa35f4bd-e360-4aa9-8d25-7c734253c64f', '2026-07-14 10:48:02.608000', 0.5,
   'excel_pilot_import', 'imported: ระดับ 1 สีนู้ด',
   'urine', 'trace', 5.0);

-- ═══════════════════════════════════════════════════════════
-- Processed 11 rows
-- ═══════════════════════════════════════════════════════════
-- Uncomment the COMMIT line to actually apply, or ROLLBACK to discard
-- COMMIT;
ROLLBACK;
